-- AlterTable
ALTER TABLE "Lead" ADD COLUMN     "adults" INTEGER DEFAULT 1,
ADD COLUMN     "budget" TEXT,
ADD COLUMN     "callDate" TIMESTAMP(3),
ADD COLUMN     "callStatus" TEXT DEFAULT 'PENDING',
ADD COLUMN     "callTime" TEXT,
ADD COLUMN     "cmNumber" TEXT,
ADD COLUMN     "daysPlanned" TEXT,
ADD COLUMN     "destination" TEXT,
ADD COLUMN     "flightCostsSent" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "followUpDate" TIMESTAMP(3),
ADD COLUMN     "followUpNote" TEXT,
ADD COLUMN     "followUpTime" TEXT,
ADD COLUMN     "hotelCategory" TEXT,
ADD COLUMN     "itineraryShared" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "kids" INTEGER DEFAULT 0,
ADD COLUMN     "kidsAge" TEXT,
ADD COLUMN     "lastVacation" TEXT,
ADD COLUMN     "mealsplan" TEXT,
ADD COLUMN     "outcome" TEXT,
ADD COLUMN     "passportStatus" TEXT,
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "quoteSent" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "remarks" TEXT,
ADD COLUMN     "returnDate" TEXT,
ADD COLUMN     "travelDate" TEXT,
ADD COLUMN     "travelFrom" TEXT,
ADD COLUMN     "travelMonth" TEXT,
ADD COLUMN     "whatsappCreated" BOOLEAN NOT NULL DEFAULT false;
